name: "transliteration"
backend: "python"
max_batch_size: 32

input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "source_script"
    data_type: TYPE_STRING
    dims: [ 1 ]
    optional: true
  },
  {
    name: "target_script"
    data_type: TYPE_STRING
    dims: [ 1 ]
    optional: true
  }
]

output [
  {
    name: "transliterated_text"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

instance_group [
  {
    count: 2
    kind: KIND_CPU
  }
]

